name : Build and Deploy Code

on : [push,pull_request]

jobs:
  job1:
    run-on: ubuntu-latest
    steps:
      - name : pulling git repo
        uses : actions/checkout@v2
      - name : say hi to sree
        run : echo "helloo sree"